#include <stdio.h>
//print function provides the outputs as evidence of execution
void triangle (int a, int b, int c){
    if ((a+b>c)&&(a+c>b)&&(b+c>a)) {
        if (a==b || a==c || b==c) {
            if (a==c && a==b)
                printf("equilateral triangle .\n");
            else if (a==c||b==c)
                printf("isosceles triangle.\n");
            //additional else statement ensure every execution provides an output
            else 
                printf("missed area.\n");
        }
        else
            printf("triangle.\n");
        }
    else
        printf("non-triangle.\n");
    return;
}

int main(){
    //declare variables
    int a,b,c;
    //use the klee command to make 
    //symbolic variables out of the inputs
    //this makes them trackable by klee
	klee_make_symbolic(&a, sizeof(a), "a");
	klee_make_symbolic(&b, sizeof(b), "b");
	klee_make_symbolic(&c, sizeof(c), "c");
    //run the function
  	triangle(a,b,c);
	return 0;
}


/**
Task:

1) Symbolic execution: a) Download and install the KLEE tool from http://klee.github.io/;
b) Apply KLEE to generate test data for the Triangle program as shown below.
2) Compute the control-flow coverage of the test data generated by KLEE, including
statement, branch decision coverage, condition coverage, condition/decision coverage,
and multiple condition coverage.

output:

    Job queued!

    Executing KLEE

    Executing KLEE

    Uploading KLEE output directory

    Done!

    Ran command "/home/klee/klee_build/bin/klee /tmp/code/code.o".

    KLEE: output directory is "/tmp/code/klee-out-0"
    KLEE: Using STP solver backend
    KLEE: WARNING: undefined reference to function: printf
    KLEE: WARNING ONCE: calling external: printf(19505824) at /tmp/code/tmp/code/code.c:1 0
    non-triangle.
    non-triangle.
    non-triangle.
    triangle.
    equilateral triangle .
    missed area. 
    isosceles triangle.
    isosceles triangle.

    KLEE: done: total instructions = 136
    KLEE: done: completed paths = 8
    KLEE: done: generated tests = 8

stats:

    Name 	    Value
    Instrs 	    136
    Time(s) 	0.2664086
    ICov(%) 	100
    BCov(%) 	100
    ICount 	    83
    TSolver(%) 	89.26175806636873

 */